### ISSUE TITLE
change Socket.gethostname to Socket.gethostbyname.

### ISSUE THREAD

**Issue by jcmartins** [sensu-plugins/sensu-plugins-aws#10]
Please see:
https://github.com/sensu/sensu-community-plugins/issues/1176
I'm have problems with amazon instance_id, please change Socket.gethostname to Socket.gethostbyname.
irb(main):002:0> Socket.gethostname
=> "master.jenkins.dev.us-east-1"
irb(main):003:0> Socket.gethostbyname(Socket.gethostname).first
=> "i-59f8d7a4.master.jenkins.dev.us-east-1.titansgroup.net"

tks
Joao

**Comment by majormoses** [comment]
@jcmartins as that link is now a 404 can you please explain more as to why this change is needed.

**Comment by majormoses** [comment]
@jcmartins which check was this from I can't see the original issue anymore.

**Comment by majormoses** [comment]
I think this issue is no longer valid after a quick scan of the code as I can't seem to find an occurance of `Socket.gethostname`.

**Comment by majormoses** [comment]
I am closing this feel free to re-open if it's still an issue.
