### ISSUE TITLE
check-elb-sum-requests.rb - bad output for influxdb

### ISSUE THREAD

**Issue by stefanocog** [sensu-plugins/sensu-plugins-aws#107]
Hi, i need store the result of this check into grafana trought influxdb but the result has not an associated metric and into grafana i view directly the result instead the metric, it's possibile to modify the script to add a metric name at the result? eg,

`<name> <result>`

intead of:

`<result>`
`CheckELBSumRequests OK: <AWS::ELB::LoadBalancer name:xxxxx>; ( within 60 seconds between 2016-03-09 09:46:05 +0100 to 2016-03-09 09:47:05 +0100)`

To grafana the output of influxdb is this:

![elb-sum](https://cloud.githubusercontent.com/assets/4162613/13630030/481ef0d0-e5dd-11e5-9a9d-37b188007cf1.png)

**Comment by eheydrick** [comment]
check style checks are not meant to output metrics. For that you'd want to use a metrics check, which outputs metrics in a format that can be put in a metrics store. For ELB metrics `metrics-elb.rb` or `metrics-elb-full.rb` can be used to collect ELB metrics. 

Alternatively you could use Grafana's built-in Cloudwatch support to access the metrics directly from Cloudwatch.
