### ISSUE TITLE
openssl should not be declared as a dependency

### ISSUE THREAD

**Issue by pmvilaca** [sensu-plugins/sensu-plugins-aws#12]
openssl is declared as a dependency in gemspec. 

```ruby
  s.add_runtime_dependency 'openssl',      '1.0.0.beta'
```
As openssl is part of the ruby core, we just need to import the module where needed but it doesn't need to be declared in gemspec.

sensu-plugins-ssl also had the same problem and it was resolved with this commit - https://github.com/sensu-plugins/sensu-plugins-ssl/commit/fd8539f2441b3ca0b907f03410da49d0a3f2a6cc

**Comment by tas50** [comment]
Fixed in https://github.com/sensu-plugins/sensu-plugins-aws/pull/13
