### ISSUE TITLE
check-elb-cert 

### ISSUE THREAD

**Issue by matthod** [sensu-plugins/sensu-plugins-aws#125]
Running the check elb cert script gives this error:

Check failed to run: undefined method `empty?' for 0:Fixnum, ["./check-elb-certs.rb:131:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

line 131 is
https://github.com/sensu-plugins/sensu-plugins-aws/blob/master/bin/check-elb-certs.rb#L131

`if !critical_message.length.empty?`

.length will always return an int, and .empty? isn't a method on an int.

Bug appears to have been introduced in recent commit where someone was attempting to clean up styling and accidentally introduced this bug: https://github.com/sensu-plugins/sensu-plugins-aws/commit/ded9399b40f966065f7174c255df05c7d5228e54

Using a version of this script one commit back fixes the issue as temp workaround.

**Comment by eheydrick** [comment]
Rubocop can be too smart sometimes. Looks like we just need to do `unless critical_message.empty?`.

**Comment by eheydrick** [comment]
Fixed with https://github.com/sensu-plugins/sensu-plugins-aws/commit/092e46fd430f60ca87ea00d823d88694c09a8091 and released in 3.2.1.
