### ISSUE TITLE
aws-sdk gem usage isn't working with ruby 2+

### ISSUE THREAD

**Issue by pmvilaca** [sensu-plugins/sensu-plugins-aws#14]
The dependency to the latest version of aws-sdk gem, is breaking a lot of checks when running with ruby 2+

This problem was already fixed in the sensu-community-plugins repo - [link to PR](https://github.com/sensu/sensu-community-plugins/pull/1047) - and the problem is also described in [this issue](https://github.com/sensu/sensu-community-plugins/issues/1018) 

We need to replace the aws-sdk dependency by aws-sdk-v1 and require aws-sdk-v1 in the checks for now, while the checks aren't changed to work with the latest version

https://rubygems.org/gems/aws-sdk-v1

**Comment by eheydrick** [comment]
Resolved by requiring aws-sdk-v1.
