### ISSUE TITLE
check elb health

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-aws#154]
It looks like the current elb health checks do not check if the minmum amout of health hosts is met. I think these events should be alerted too...

Furthermore I am confused about three different health check scripts, check-elb, check-elb-fox, check-elb-sdk...

I would prefer a single working script here. What is your plan for the future? Would it make sense to create a pull request for this feature? Which api/sdk do you want to use?

**Comment by runningman84** [comment]
@sstarcher please advice...

**Comment by sstarcher** [comment]
The preference would be for aws_sdk v2.  I'm guessing those scripts are old and if fully implemented under aws_sdk v2 could be gotten rid of.
