### ISSUE TITLE
CheckInstanceCount - There was an error reaching AWS - uninitialized constant

### ISSUE THREAD

**Issue by z-matth** [sensu-plugins/sensu-plugins-aws#180]
CMD:
./check-instances-count.rb -g aMY_ASG -w 5 -c 10

ERROR:
CheckInstanceCount CRITICAL: There was an error reaching AWS - uninitialized constant CheckInstanceCount::AWS
Did you mean?  Aws

**Comment by majormoses** [comment]
looks like someone tried upgrading the aws sdk to v2 and did missed something. I can work on a pr for this.

**Comment by majormoses** [comment]
@z-matth I have created a pr to address (of course I had to push when github was having issues) please let me know if you have any issues with my fork.

**Comment by z-matth** [comment]
I just tested using your commit. Worked great. Thanks!
