### ISSUE TITLE
Feature Requests / Questions?

### ISSUE THREAD

**Issue by tdotgreenshirt** [sensu-plugins/sensu-plugins-aws#186]
- metrics-rds.rb is not included in the latest tagged version. Is there a reason for this?

- I recently submitted a pull request to include the flags to pass the access key and secret in metrics-rds.rb, but it was denied because I was told the intended way was to pass through environment variables. How do we do this?

 - metrics-rds.rb doesn't seem to include all of the statistics for an Aurora DB, whereas when running this on a MySQL DB, this works as intended. Clearly, the AWS console provides this information for both types, but this check doesn't seem to support both.

Example output for checking an Aurora DB:
xxxxxx.databaseconnections 93.0 1481824800
xxxxxx.binlogdiskusage 0.0 1481824800

 - Is there a check I can use to ensure each specified availability zone is up? Else, warn if down at a specified time (seconds) and critical at another specified period (seconds).

 - Support for checks and metrics for ALBs

Thanks

**Comment by runningman84** [comment]
I think we just need a new release to have metrics-rds and others included. @eheydrick when do you plan a new release?

The access und secret keys are environment variables like these:
```
export AWS_ACCESS_KEY_ID="AKIAXXXXXXXXXXXXXXXXXX"
export AWS_SECRET_ACCESS_KEY="12345zzzzzzzzzzzzzzzz"
```
Just export them and the sensu aws plugin should use them by default. I would also recommend to use IAM profiles.

I would suggest to just create a pull request for supporting Aurora databases.

My team spend a lot of time improving (sdk2 migration) checks and adding new ones. There will be additional pull requests in the future. Maybe ALB checks will be included too.

**Comment by eheydrick** [comment]
Working on cutting a new release.

**Comment by eheydrick** [comment]
4.0.0 is out on Rubygems. Credentials should be set in environment variables, a credential file, or with an IAM instance profile. See http://docs.aws.amazon.com/sdkforruby/api/#Configuration for details on setting credentials.
