### ISSUE TITLE
check-instance-health.rb : not able check more then 100 instance 

### ISSUE THREAD

**Issue by dkdhinakaran** [sensu-plugins/sensu-plugins-aws#195]
CheckInstanceEvents UNKNOWN: An error occurred processing AWS EC2 API: 136 exceeds the maximum number of instance IDs that can be specificied (100). Please specify fewer than 100 instance IDs.

**Comment by majormoses** [comment]
Can you give a little bit of information on how you are using this and which check it is? I would suspect based on the error message that we need to look at the number of instance ids and batch them with > 100 instances.

**Comment by majormoses** [comment]
Taking a quick look it looks like you might be able to work around this using a filter and we can look at adding some sort of batching. Would filters work for you in the short term?

**Comment by majormoses** [comment]
@dkdhinakaran I have a pr that allows batching of requests to remove 100 instance id limit per request, let me know if you have any feedback or issues.
