### ISSUE TITLE
How to use the plugin for cloudwatch metrics

### ISSUE THREAD

**Issue by rajiv-g** [sensu-plugins/sensu-plugins-aws#215]
Need help to trigger sensu alert based on cloudwatch metrics. How can I implement it?

**Comment by eheydrick** [comment]
I see you sent a message to the mailing list. Check my response and let me know if you have any further questions.

**Comment by rajiv-g** [comment]
As per discussion on mailing list, I have created issue #219

**Comment by majormoses** [comment]
closing per: https://github.com/sensu-plugins/sensu-plugins-aws/issues/219#issuecomment-313880172
