### ISSUE TITLE
openssl dependency is broken

### ISSUE THREAD

**Issue by seanmcl** [sensu-plugins/sensu-plugins-aws#22]
https://rubygems.org/gems/openssl

I think you just need to remove the dependency, as was done here.

https://github.com/sensu-plugins/sensu-plugins-graphite/issues/3

msg: ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: sensu-plugins-aws requires openssl (= 1.0.0.beta)
failed: [core-prod13.eglp.com] => (item=sensu-plugins-aws) => {"cmd": "/bin/gem install --version 0.0.2 --no-user-install --no-rdoc --no-ri sensu-plugins-aws", "failed": true, "item": "sensu-plugins-aws", "rc": 1}
stderr: ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: sensu-plugins-aws requires openssl (= 1.0.0.beta)

**Comment by tas50** [comment]
We have this fixed on master.  We just need to push the new gem

**Comment by NeckBeardPrince** [comment]
Know when that might be pushed?
