### ISSUE TITLE
This plugin does not yet support 0.29 because of version conflicting versions of `sensu-plugin`

### ISSUE THREAD

**Issue by z-matth** [sensu-plugins/sensu-plugins-aws#220]
All other checks work fine. ELB, RDS, etc. No issues. This is only one that fails on my rig.

sensu version = 0.29
/opt/sensu/embedded/bin/ruby = ruby 2.4.1p111

the exact command i'm running is:
/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/sensu-plugins-aws/bin/check-reserved-instances.rb -w 2592000 -c 259200

and the error is:
>/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate sensu-plugins-aws-6.1.0, because sensu-plugin-2.0.1 conflicts with sensu-plugin (~> 1.3) (Gem::ConflictError)
>	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1408:in >`activate'
>	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
>	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
>	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
>	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in >`require'
>	from /etc/sensu/plugins/sensu-plugins-aws/bin/check-reserved-instances.rb:30:in`\<main>'

I tried removing and installing gems from scratch. i can't remove old gems w/o breaking other plugins.

full gem list as follows:
*** LOCAL GEMS ***

activesupport (4.2.9, 4.2.6)
addressable (2.5.1)
amq-protocol (2.0.1)
amqp (1.6.0)
aws-es-transport (0.1.4)
aws-sdk (2.10.4, 2.4.4)
aws-sdk-core (2.10.4, 2.4.4)
aws-sdk-resources (2.10.4, 2.4.4)
aws-sdk-v1 (1.67.0, 1.66.0)
aws-ses (0.6.0)
aws-sigv4 (1.0.0)
bigdecimal (default: 1.3.0)
bson (4.2.1)
builder (3.2.3)
bunny (2.5.0)
carrot-top (0.0.7)
CFPropertyList (2.3.5)
childprocess (0.5.8)
chronic_duration (0.10.6)
cookiejar (0.3.3)
did_you_mean (1.1.0)
dnsbl-client (1.0.2)
dnsruby (1.60.1)
domain_name (0.5.20170404)
elasticsearch (1.1.2, 1.0.14)
elasticsearch-api (5.0.4, 1.1.2, 1.0.18, 1.0.14)
elasticsearch-transport (5.0.4, 1.1.2, 1.0.18, 1.0.14)
em-http-request (1.1.5)
em-http-server (0.1.8)
em-socksify (0.3.1)
em-worker (0.0.2)
english (0.6.3)
erubis (2.7.0)
eventmachine (1.2.2)
excon (0.57.0)
faraday (0.9.2)
faraday_middleware (0.10.1)
ffi (1.9.18)
fission (0.5.0)
fog (1.32.0)
fog-atmos (0.1.0)
fog-aws (1.4.0)
fog-brightbox (0.11.0)
fog-core (1.43.0)
fog-ecloud (0.1.1)
fog-google (0.5.3)
fog-json (1.0.2)
fog-local (0.3.1)
fog-powerdns (0.1.1)
fog-profitbricks (3.0.0)
fog-radosgw (0.0.5)
fog-riakcs (0.1.0)
fog-sakuracloud (1.7.5)
fog-serverlove (0.1.2)
fog-softlayer (1.1.4)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-xml (0.1.3)
formatador (0.2.5)
http-cookie (1.0.3)
http_parser.rb (0.6.0)
i18n (0.8.4)
inflecto (0.0.2)
inifile (3.0.0)
io-console (default: 0.4.6)
ipaddress (0.8.3)
jenkins_api_client (1.5.3)
jmespath (1.3.1)
json (default: 2.0.2, 1.8.6)
language (0.6.0)
mail (2.6.6)
mime-types (3.1, 2.99.3)
mime-types-data (3.2016.0521)
mini_portile2 (2.2.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
mixlib-shellout (2.2.7)
mongo (2.4.1)
mono_logger (1.1.0)
multi_json (1.12.1)
multipart-post (2.0.0)
mustermann (1.0.0)
net-ping (1.7.8)
net-telnet (0.1.1)
netrc (0.11.0)
nokogiri (1.8.0)
numerizer (0.1.1)
oj (2.18.1)
openssl (default: 2.0.3)
pagerduty (2.1.0)
parse-cron (0.1.4)
power_assert (0.4.1)
psych (default: 2.2.2)
public_suffix (2.0.5)
rack (2.0.3)
rack-protection (2.0.0)
raindrops (0.18.0)
rake (12.0.0)
rake-compiler (1.0.3)
rb-readline (0.5.3)
rdoc (default: 5.0.0)
redis (3.3.3)
redis-namespace (1.5.3)
resque (1.25.2)
rest-client (1.8.0)
right_aws (3.1.0)
right_http_connection (1.5.0)
ruby-mysql (2.9.14)
rubygems-update (2.6.10)
sensu (0.29.0)
sensu-extension (1.5.1)
sensu-extensions (1.9.0)
sensu-extensions-check-dependencies (1.0.1)
sensu-extensions-debug (1.0.0)
sensu-extensions-json (1.0.0)
sensu-extensions-occurrences (1.2.0)
sensu-extensions-only-check-output (1.0.0)
sensu-extensions-ruby-hash (1.0.0)
sensu-json (2.1.0)
sensu-logger (1.2.1)
sensu-plugin (2.0.1, 1.4.5, 1.2.0)
sensu-plugins-apache (0.0.5)
sensu-plugins-aws (6.1.0)
sensu-plugins-disk-checks (2.2.0)
sensu-plugins-dns (1.2.1)
sensu-plugins-elasticsearch (1.3.1)
sensu-plugins-filesystem-checks (0.2.0)
sensu-plugins-github (2.0.0)
sensu-plugins-http (2.4.0)
sensu-plugins-load-checks (3.0.0)
sensu-plugins-memory-checks (2.1.0)
sensu-plugins-mongodb (1.3.0)
sensu-plugins-mysql (2.1.1)
sensu-plugins-network-checks (2.0.0)
sensu-plugins-nginx (2.1.0)
sensu-plugins-ntp (1.0.1)
sensu-plugins-openvpn (0.0.3)
sensu-plugins-postfix (0.1.0)
sensu-plugins-process-checks (2.3.0)
sensu-plugins-rabbitmq (3.2.0)
sensu-plugins-resque (0.1.0)
sensu-plugins-sensu (1.1.0)
sensu-plugins-slack (1.1.1)
sensu-plugins-ssl (1.4.0)
sensu-plugins-uchiwa (1.0.0)
sensu-redis (2.1.1)
sensu-settings (10.0.0)
sensu-spawn (2.2.1)
sensu-transport (7.0.2)
sinatra (2.0.0)
socksify (1.7.1)
stomp (1.4.3)
sys-filesystem (1.1.7)
sys-proctable (0.9.8 universal-linux)
terminal-table (1.8.0)
test-unit (3.2.3)
thor (0.19.4)
thread_safe (0.3.6)
tilt (2.0.7)
tzinfo (1.2.3)
unf (0.1.4)
unf_ext (0.0.7.4)
unicode-display_width (1.3.0)
vegas (0.1.11)
whois (3.6.3)
xml-simple (1.1.5)
xmlrpc (0.2.1)

**Comment by majormoses** [comment]
@z-matth Thanks for the report. This plugin does not support version 2.x yet we are working on it across all plugins but will take some time and effort to get us all there safely. You can read more about it and has some information if you want to help get involved: https://blog.sensuapp.org/community-maintenance-mode-d109e75bcbc4

Until we can get all the dependencies safely downgrade to 0.28 and pin it until we are ready.

**Comment by autarchprinceps** [comment]
So it doesn't work on 0.29, but 1.0 is released all ready. It would really be great if you fixed this.

**Comment by majormoses** [comment]
Ya I agree, we have now done the install testing within the last week or so but we now need to run though and do runtime testing and then we can bump. If you would like to contribute some time this can go faster. But currently there are 2 active maintainers (neither of us working for sensu) on 180+ plugins and we will get around to it, just takes time.

**Comment by majormoses** [comment]
fixed via #228 and released in https://rubygems.org/gems/sensu-plugins-aws/versions/7.0.0
