### ISSUE TITLE
check-asg-instances-created check fails due to int and string comparison

### ISSUE THREAD

**Issue by cihangirbesiktas** [sensu-plugins/sensu-plugins-aws#221]
I got the following error in the check.

`# check-asg-instances-created.rb -r us-east-1 -g my_asg -w 1 -c 2
Check failed to run: comparison of Integer with String failed, ["/usr/local/bundle/gems/sensu-plugins-aws-6.1.0/bin/check-asg-instances-created.rb:121:in `>='", "/usr/local/bundle/gems/sensu-plugins-aws-6.1.0
/bin/check-asg-instances-created.rb:121:in `run'", "/usr/local/bundle/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
#`

I resolved the problem by making `config[:warning_limit]` to `config[:warning_limit].to_i` in line 81 and `config[:critical_limit]` to `config[:critical_limit].to_i` in line 83

**Comment by majormoses** [comment]
fixed in #222
