### ISSUE TITLE
Create major (breaking) release without aws sdk v1

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-aws#240]
It is not possible to install the aws plugins with the latest sensu releases:
```
`Unable to activate aws-sdk-v1-1.66.0, because json-2.1.0 conflicts with json (~> 1.4)` `json (2.1.0, default: 2.0.2, 1.8.6)`
```
In order to fix this I would propose the release of a new major release without any v1 checks.

**Comment by majormoses** [comment]
@runningman84 thanks for raising the issue, I think we need to first take a look at the impact on the number of checks and either need to make a decision to remove or update them. ping @eheydrick

**Comment by eheydrick** [comment]
Of the 76 checks, 11 are still using aws-sdk v1. I think we should put in the effort to update them to v2.

check-elb-certs.rb
check-elb-health-sdk.rb
check-elb-latency.rb
check-elb-nodes.rb
check-elb-sum-requests.rb
check-redshift-events.rb
handler-ses.rb
handler-sns.rb
metrics-ec2-count.rb
metrics-elb-full.rb
metrics-sqs.rb

**Comment by eheydrick** [comment]
5 checks have been updated to AWS-SDK v2 and released in 9.0.0. 6 left to update.
https://rubygems.org/gems/sensu-plugins-aws/versions/9.0.0.

**Comment by majormoses** [comment]
I will try to take these ones this weekend:
-  `check-elb-latency.rb`
- `check-elb-sum-requests.rb`

**Comment by majormoses** [comment]
I added the handlers as they also required v1

**Comment by eheydrick** [comment]
I have `handler-ses` almost ready to PR. Going to do `handler-sns` after that.

**Comment by eheydrick** [comment]
Handlers have been updated for AWS-SDK v2 and released in 10.0.0. Going to update the remaining 4 checks next. https://rubygems.org/gems/sensu-plugins-aws/versions/10.0.0

**Comment by majormoses** [comment]
Sorry I have been super busy if I have some time I will get to it but if someone has the time feel free to jump in.

**Comment by eheydrick** [comment]
I have `check-elb-latency` just about ready to PR.

**Comment by multani** [comment]
As a side note, ``check-elb-health-fog.rb`` and ``check-elb-health.rb`` are the only plugins not using the AWS SDK (nor v1 nor v2), but as explained in https://github.com/sensu-plugins/sensu-plugins-aws/issues/254#issuecomment-348754980 I think they could be removed in favor of ``check-elb-health-sdk.rb`` which should do the same job as the two others.

**Comment by majormoses** [comment]
@multani thanks for helping out with this!

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-aws/versions/16.0.0
