### ISSUE TITLE
check-rds-events.rb timestamp must follow ISO8601

### ISSUE THREAD

**Issue by jorge-cloudmas** [sensu-plugins/sensu-plugins-aws#278]
From a time to this part (a week) the check of rds vents is not working properly.
As the message indicates, there seems to be an error with the time format:

CheckRDSEvents UNKNOWN: An error occurred processing AWS RDS API (eu-west-1): timestamp must follow ISO8601

I understand that it may be a failure of the AWS API

clusters.each do |cluster_name|
          events_record = rds.describe_events(start_time: (Time.now - 900).iso8601, source_type: 'db-instance', source_identifier: cluster_name)
          next if events_record[:events].empty?

**Comment by nadarashwin** [comment]
We are facing the same issue and it's definitely to do with the timestamp as when we remove 'start_time' argument it works fine.
`events_record = rds.describe_events( source_type: 'db-instance', source_identifier: cluster_name)`

**Comment by jorge-cloudmas** [comment]
Right!!
I made the same change and works fine.
This is a problem for us,  we update directly from github all the sensu-servers with the same issue.
Will an update be made to solve this problem?

Thanks again nadarashwin,
Regards

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-aws/versions/11.3.1

fixed in #279
