### ISSUE TITLE
handler to remove only aws instance that are stopped or terminated.

### ISSUE THREAD

**Issue by jcmartins** [sensu-plugins/sensu-plugins-aws#4]
The ec2_node remove the sensu-client in Uchiwa when it's stopped.

but i don't like this because it's can be a problem in the sensu-client. So I want remove the keepalive when the instance status are stopped or terminated.

**Comment by bkett** [comment]
So per discussion in IRC the actual issue is related to how ec2_node_exists? is defined in the handler. I'm going to default to the source which says in this case either extend the class to override the method, or fork and alter the implementation of the handler to suit your needs.

It may be worth adding this functionality in the second iteration for refactoring.

**Comment by mattyjones** [comment]
As a side note:

* [graceful-shutdown-keepalive.rb[(https://github.com/yieldbot/sensu-yieldbot-plugins/blob/master/handlers/other/graceful-shutdown-keepalive.rb)
* [graceful-shutdown.rb](https://github.com/yieldbot/sensu-yieldbot-plugins/blob/master/handlers/other/graceful-shutdown.rb)
* [sensu-socket-client.rb](https://github.com/yieldbot/sensu-yieldbot-plugins/blob/master/plugins/sensu/sensu-socket-client.rb)
* [sensu-socket-client.rb](https://github.com/yieldbot/sensu-yieldbot-plugins/blob/master/plugins/sensu/sensu-socket-client.rb)

The rough idea is that when a graceful shut is kicked and init script notifies the client.  The client then sends a json blurb to the server.  The handler makes an api call to remove the client from the dashboard and creates a stash.  Our keepalive checks this stash before sending an alert.

@bkett @jcmartins

**Comment by bkett** [comment]
Ah ok that's a cool alternative @mattyjones. Yeah if this isn't needed I won't work on it and anyways it's not on my todo for the current scope.

**Comment by jcmartins** [comment]
tks

**Comment by ravvereddy** [comment]
@mattyjones 

Can you please guide me in achieving this.

How to remove the clients from the uchiwa dashboard if the instance is either terminated or stopped.

I tried to install, the graceful-shutdown-keepalive.rb plugin and did not work for me.

Please help me out how i can achieve this.

Thanks
