### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by mnuessler** [sensu-plugins/sensu-plugins-aws#48]
Just a question: Is a new release planned any time soon for this plugin? That last release was in August and new checks have been added since then (i.e. check-s3-object) which would be very useful for us.

**Comment by obazoud** [comment]
:+1:

**Comment by eheydrick** [comment]
@tas50, @analytically, @mattyjones, want to cut a new release. I just updated the CHANGELOG.

**Comment by eheydrick** [comment]
sensu-plugins-aws 2.0.0 has been released.

**Comment by obazoud** [comment]
Thank you!

and don't forget to tag the release ;)

**Comment by mattyjones** [comment]
All releases are tagged and pushed to rubygems. Not sure why this one didn't get a new tag. I will look into it and in the meantime push a tag myself.

**Comment by eheydrick** [comment]
The curl that creates the tag is failing. I think the booleans (like draft and prerelease) need to not be quoted or something.

**Comment by mattyjones** [comment]
@eheydrick  I will fix that. If you pull 1.9.3 compatibility you also need to adjust the gemspec and such (I can do this as well). I will then cut a new 2.1 to reflect this and the dependency pins, etc. :)

**Comment by mattyjones** [comment]
@eheydrick @obazoud  New tag and gem pushed 2.0.1

**Comment by obazoud** [comment]
Thanks a lot!

**Comment by eheydrick** [comment]
Thanks @mattyjones.
