### ISSUE TITLE
handler-ec2_node.rb : Using client's region  instead of sensu-server's ?

### ISSUE THREAD

**Issue by frederic-joventures** [sensu-plugins/sensu-plugins-aws#53]
Hello, 
would it be possible to use the client region instead of the sensu region ?
for ex if I put the region inside the client json config file I guess we could use it to send to the correct region ?

My problem is that I have servers in a lot of regions.

**Comment by runningman84** [comment]
Furthermore it would be great if the handler could check every region if nor region is specified or known...

**Comment by runningman84** [comment]
That should solve this:
https://github.com/sensu-plugins/sensu-plugins-aws/pull/132

**Comment by runningman84** [comment]
@eheydrick please close this...

**Comment by cwjohnston** [comment]
Closed by #132, released in 3.2.0
