### ISSUE TITLE
aws-sdk-v1 error to install nokogiri dependecy

### ISSUE THREAD

**Issue by jcmartins** [sensu-plugins/sensu-plugins-aws#57]
Hi,
I have problems to install **aws-sdk-v1** on ubuntu instance because a nokogiri error.
I needed do:
**apt-get install libxml2 libxml2-dev libxslt1-dev libxslt1.1**
and run:
**/opt/sensu/embedded/bin/gem install 'nokogiri -- --use-system-libraries --with-xml2-include=/usr/include/libxml2/'**
so I can install it:
**/opt/sensu/embedded/bin/gem install aws-sdk-v1**

**Comment by eheydrick** [comment]
The README says you need to install the `build-essential libxml2-dev zlib1g-dev` packages. aws-sdk-v1 depends on nokogiri so you don't need to install it separately.
