### ISSUE TITLE
error CheckRDS::Common (NameError)

### ISSUE THREAD

**Issue by jcmartins** [sensu-plugins/sensu-plugins-aws#68]
After I did the check-rds  upgrade to use the version 2 of aws-sdk

/etc/sensu/plugins/checks/check_rds.rb:58:in `<class:CheckRDS>': uninitialized constant CheckRDS::Common (NameError) from /etc/sensu/plugins/checks/check_rds.rb:57:in `<main>'
Invalid check argument(s): invalid option: -i, ["/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:191:in `parse_options'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:13:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:55:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:55:in `block in <class:CLI>'"]

**Comment by eheydrick** [comment]
Which version of the plugin are you using? check-rds is still written for aws-sdk-v1.

**Comment by eheydrick** [comment]
@jcmartins any update?
