### ISSUE TITLE
Is there a reason still using AWS SDK V1

### ISSUE THREAD

**Issue by zbintliff** [sensu-plugins/sensu-plugins-aws#69]
The V1 SDK is outdated and most newer features of AWS sources are not supported on it.  Is there aversion to updateding to SDK core? 

Would a new gem version be enough of an upgrade. or should we create side by side scripts?

**Comment by eheydrick** [comment]
Moving to v2 is in progress in PR https://github.com/sensu-plugins/sensu-plugins-aws/pull/52.

**Comment by zbintliff** [comment]
Ah great thanks, Will comment on that to use ec instance profiles too instead of manually passing content.

Thanks
