### ISSUE TITLE
New Release soon?

### ISSUE THREAD

**Issue by jessechahal** [sensu-plugins/sensu-plugins-aws#71]
I was trying to figure out what the release schedule is for rubgems but it seems to be on-demand. I was hoping you guys would consider doing a release soon as I see quite a few changes that my team is currently trying to take advantage of but have not yet reached the latest release (2.0.1). Are there plans to release anytime soon or would it be recommended that we start building our own gem? 

One change that comes to mind is support of newer instance types for rds: 
https://github.com/sensu-plugins/sensu-plugins-aws/commit/224484dbd1bc6d6059fc49898086c934c4cd7a06

**Comment by eheydrick** [comment]
Hi @jessechahal, we try to release shortly after changes are merged. I'm working on getting a new release out soon.

**Comment by eheydrick** [comment]
CHANGELOG has been updated. I'd like to get a README update for https://github.com/sensu-plugins/sensu-plugins-aws/pull/65 in and then we can cut a new release.

**Comment by jessechahal** [comment]
Awesome, thanks for the quick response!

**Comment by jamengual** [comment]
That do you want me to update in the README ? the handler-ec2.rb readme has been updated and I don't see any reference on sensu-plugins-aws/README to any handler so I'm unsure what I should update.

Thanks.

**Comment by eheydrick** [comment]
2.1.0 has been released.

**Comment by eheydrick** [comment]
@jamengual the docs in the plugin look sound to me. Some plugins are documented in the README, some in the plugins. Would be good to standardize.

**Comment by jamengual** [comment]
agreed
