### ISSUE TITLE
check_vpc_vpn.py tries to run as Ruby script rather than Python script

### ISSUE THREAD

**Issue by willbuckner** [sensu-plugins/sensu-plugins-aws#81]
# check_vpc_vpn.py -v vpn-xxxxxxx

```
/usr/local/bin/check_vpc_vpn.py:23:in `load': /var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:10: syntax error, unexpected ':' (SyntaxError)
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:13: syntax error, unexpected ':', expecting keyword_end
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:18: syntax error, unexpected ':', expecting keyword_do_cond or ';' or '\n'
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:19: syntax error, unexpected ':'
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:20: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:21: syntax error, unexpected ')', expecting '='
...side_ip_address, tunnel.status))
...                               ^
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:23: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:26: syntax error, unexpected ':', expecting ')'
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:29: syntax error, unexpected keyword_else, expecting ')'
    else:
        ^
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:33: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py:42: syntax error, unexpected end-of-input, expecting ')'
    from /usr/local/bin/check_vpc_vpn.py:23:in `<main>'
root@shared-monitoring-1b:~# /usr/bin/python /var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py
usage: check_vpc_vpn.py [-h] -a AWS_ACCESS_KEY_ID -s AWS_SECRET_ACCESS_KEY -r
                        REGION
check_vpc_vpn.py: error: argument -a/--aws-access-key-id is required
```

This was installed via `gem install sensu-plugins-aws`. The file it created at `/usr/local/bin/check_vpc_vpn.py` is:

```
#!/usr/bin/ruby2.1
#
# This file was generated by RubyGems.
#
# The application 'sensu-plugins-aws' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
    str = ARGV.first
    str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
    if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
       version = $1
       ARGV.shift
   end
end

gem 'sensu-plugins-aws', version
load Gem.bin_path('sensu-plugins-aws', 'check_vpc_vpn.py', version)
```

**Comment by zbintliff** [comment]
Thats how Gem scripts work so you don't have to deal with your GEM_ENV.  If you want to run the script itself just run it from your gem path directly and if the shebang is python it should work.

it looks like it is: `/var/lib/gems/2.1.0/gems/sensu-plugins-aws-2.1.0/bin/check_vpc_vpn.py`

**Comment by willbuckner** [comment]
So can we make this one not install in `/usr/local/bin` at all then? I mean, it may be a Gem limitation, but the installation of this script is definitely broken. Is there any way to customize these Gem loader scripts? It seems to me like it should `Gem.bin_path('sensu-plugins-aws', 'check_vpc_vpn.py', version)` and use the result in an `exec` of the Python script.

Maybe the Python version shouldn't be included here at all, if we can get the Ruby version working again (it's currently broken).

**Comment by eheydrick** [comment]
There's a ruby version of check-vpc-vpn at `check-vpc-vpn.rb`. Any reason that won't work?

**Comment by zbintliff** [comment]
@willbuckner the ruby script is probably only broken now because of the aws gem upgrade.  If you pin the sensu-plugins-aws gem back to an older version it should continue to work.

**Comment by willbuckner** [comment]
This is addressed in #79 and I fixed it in a pull request #83 if you could merge that! :) It was using `aws-sdk-v1` syntax in `aws-sdk`. Some other portions depend on v2 so pinning it would just break other things. We should update it to use v2, but in the mean time, it should just require v1 like some other components do. If we depend on a specific version of v2, we should depend on that explicitly anyway right?

**Comment by analytically** [comment]
So this can be closed?

**Comment by willbuckner** [comment]
This shouldn't be closed unless the Python script is fixed or removed.

**Comment by eheydrick** [comment]
What would you like to see in the ruby version that's missing? Looks like the main difference is that the python one checks all VPNs whereas the ruby one checks specified VPNs.

**Comment by willbuckner** [comment]
I think the Ruby version is fine the way it is (for now at least); my PR was merged and the dependency issue was fixed. But installation of the Python script is clearly broken, so it should either be fixed or removed. Why keep a Python version in repository HEAD if the Ruby version works fine and the Python version can't be run?

**Comment by majormoses** [comment]
@willbuckner I agree I will create a PR for removing the python check and will cut a major release after it is merged.
